### PR TITLE
#0rQ4rIV6 Initial Development

### PR DESCRIPTION
**Pull request by localjo**
See: https://trello.com/c/0rQ4rIV6/1219-wordpress-load-publishing-latency

This plugin should purge the WP-API resources in storyteller.io for any relevant actions.

It will have a configurable storyteller project name and API key.

### CODE REVIEW

**Comment by localjo** [comment]
The WordPress Action Reference isn't 100% complete so I'll need to test the actions I stubbed out to make sure they're triggered in the right circumstances, and not triggered more than once from one user action.

**Comment by localjo** [comment]
This is a working first prototype. Things that still need to be done;
- [x] Check if Storyteller settings have been entered before adding action hooks.
- [x] Write some logic to determine which routes to clear
- [x] Show confirmation of routes cleared on WP edit page
- [x] Test on with actual cached resources, on updated storyteller version with cache clearing

@pushred @joanniclaborde Right now I'm just clearing `/pages` and `/posts` on `post_updated`, and `/media` on `add_`, `edit_` and `delete_attachment`. What other routes need to be cleared? I suppose I should use the post or attachment ID to clear the specific route for the item being updated. I could also check post categories and clear the category routes. Are there any other major routes that come to mind that need to be cleared?

**Comment by joanniclaborde** [comment]
Your best bet is to take a few sites, and grep the WordPress resources. You'll quickly see which paths are used.

**Comment by localjo** [comment]
When posts are updated, this will make a `PUT` request to `http://proxy.storyteller.io/wordpress-rest-api/{site-subdomain}/{route}` with `Project` and `Api-Key` headers set based on values entered in the WP dashboard, where `site-subdomain` is the WP install's subdomain for the current site, and `route` is the determined by the plugin based on which type of post was updated.

**Comment by localjo** [comment]
Some UX problems I'm seeing with this plugin;
1) The storyteller proxy URL is [hard coded](https://github.com/SparkartGroupInc/storyteller-helper/blob/initial-development/storyteller-helper.php#L41). It might make sense to make that a configurable option, to make it easier to switch between dev and staging.
2) If cache clearing of a particular route fails, no errors are displayed, but it might make sense to display some sort of error. Even if content editors don't understand the error, they'll at least be notified that the cache wasn't able to be cleared.

I'm also not seeing the staging Storyteller cache being cleared after a `PUT` request to the resource, as described [here](https://github.com/SparkartGroupInc/hipster/pull/120), but I may be misunderstanding how that's supposed to work.

**Comment by josiahsprague** [comment]
Here is an example of the notices I'm displaying when a post is updated. screen shot 2015-07-15 at 1 17 55 pm

I think the post updated message should come first, and maybe the color bars on the left hand side of the notices shouldn't be red or green, since they aren't giving feedback about whether the post itself was actually updated.

**Comment by localjo** [comment]
I added an option for the Storyteller proxy URL in the admin, and added better feedback regarding which routes were cleared, and which failed to clear. 
screen shot 2015-07-15 at 1 26 25 pm

**Pull request merged**
